"""Initial migration with new models

Revision ID: 9a8a823d25f0
Revises: 
Create Date: 2025-09-08 16:44:10.448831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8a823d25f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pondoks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pondok_id', sa.String(length=500), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('pondok_name', sa.String(length=500), nullable=False),
    sa.Column('access_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_code'),
    sa.UniqueConstraint('pondok_id')
    )
    op.create_table('guru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=500), nullable=False),
    sa.Column('mengajar_kelas', sa.String(length=500), nullable=False),
    sa.Column('pondok_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pondok_id'], ['pondoks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('santri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=500), nullable=False),
    sa.Column('kelas', sa.String(length=500), nullable=True),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('tercapai', sa.Boolean(), nullable=True),
    sa.Column('total_hafalan_juz', sa.Integer(), nullable=True),
    sa.Column('target_harian', sa.String(length=500), nullable=True),
    sa.Column('target_mingguan', sa.String(length=500), nullable=True),
    sa.Column('target_bulanan', sa.String(length=500), nullable=True),
    sa.Column('target_tahunan', sa.String(length=500), nullable=True),
    sa.Column('pondok_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pondok_id'], ['pondoks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hafalan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('setoran', sa.String(length=500), nullable=False),
    sa.Column('jenis', sa.String(length=500), nullable=False),
    sa.Column('penilaian', sa.String(length=500), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('pondok_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pondok_id'], ['pondoks.id'], ),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hafalan')
    op.drop_table('santri')
    op.drop_table('guru')
    op.drop_table('pondoks')
    # ### end Alembic commands ###
